# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbdr < Formula
  desc ""
  homepage "https://github.com/jkassis/homebrew-keg"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jkassis/jerriedr/releases/download/v0.1.4/jerriedr_0.1.4_darwin_arm64.tar.gz"
      sha256 "c97bb4224444fd3409c937ffe1731992a8fa3a3757fef306c446f87408efb08f"

      def install
        bin.install "jerriedr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jkassis/jerriedr/releases/download/v0.1.4/jerriedr_0.1.4_darwin_amd64.tar.gz"
      sha256 "262364feb92bcc4bb22c6b64520b9c1654306839b329c50202d72927ba9abea5"

      def install
        bin.install "jerriedr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jkassis/jerriedr/releases/download/v0.1.4/jerriedr_0.1.4_linux_arm64.tar.gz"
      sha256 "c2dbd6bf69f525d5e9e75e4ec2248232be628f29a03c7b382c73d84b0fe889d6"

      def install
        bin.install "jerriedr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jkassis/jerriedr/releases/download/v0.1.4/jerriedr_0.1.4_linux_amd64.tar.gz"
      sha256 "088489273ee8c7ba69c3f2759324c79af7ddc3940f6ccd598cd862b776874b06"

      def install
        bin.install "jerriedr"
      end
    end
  end
end
