# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitall < Formula
  desc ""
  homepage "https://github.com/jkassis/homebrew-keg"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jkassis/gitall/releases/download/v0.6.1/gitall_0.6.1_darwin_amd64.tar.gz"
      sha256 "2d6567a53726efa84c9ec53e07aad915621f94afd67b2636199fd075bf33c0aa"

      def install
        bin.install "gitall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jkassis/gitall/releases/download/v0.6.1/gitall_0.6.1_darwin_arm64.tar.gz"
      sha256 "c641a36a24762c5b41adf9c01a6e5238aa0a3e265650ce2db395992becfb5892"

      def install
        bin.install "gitall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jkassis/gitall/releases/download/v0.6.1/gitall_0.6.1_linux_arm64.tar.gz"
      sha256 "4b4a6e6c6b2c35e8c274c27a4a203a1ffd3fc8b2aa94b2eb76d32730a25c481b"

      def install
        bin.install "gitall"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jkassis/gitall/releases/download/v0.6.1/gitall_0.6.1_linux_amd64.tar.gz"
      sha256 "8dff470a3661c2fbb953048bdcf871a1bcee13d35482962918bba2b9edb237f0"

      def install
        bin.install "gitall"
      end
    end
  end
end
