# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jerriedr < Formula
  desc ""
  homepage "https://github.com/jkassis/homebrew-keg"
  version "0.2.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jkassis/jerriedr/releases/download/v0.2.12/jerriedr_0.2.12_darwin_amd64.tar.gz"
      sha256 "6cc8e686888238b44fc79d1ea784e5fa4ecd79dbb584b0dfe55dd995bb2dd483"

      def install
        bin.install "jerriedr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jkassis/jerriedr/releases/download/v0.2.12/jerriedr_0.2.12_darwin_arm64.tar.gz"
      sha256 "33df0e5cd7443c408de0b6695544ace03d1b10276cf00f3fa4a142d8d7f60915"

      def install
        bin.install "jerriedr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jkassis/jerriedr/releases/download/v0.2.12/jerriedr_0.2.12_linux_arm64.tar.gz"
      sha256 "725b951396cd2bdbc3239218d53a49f21de1db35b9bd780e1246d323b874d33d"

      def install
        bin.install "jerriedr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jkassis/jerriedr/releases/download/v0.2.12/jerriedr_0.2.12_linux_amd64.tar.gz"
      sha256 "2cf09626a2bd40d020e7d9ad47d5b9071144da033de29ab782aed4dac8f11ce7"

      def install
        bin.install "jerriedr"
      end
    end
  end
end
