# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jerriedr < Formula
  desc ""
  homepage "https://github.com/jkassis/homebrew-keg"
  version "0.2.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jkassis/jerriedr/releases/download/v0.2.13/jerriedr_0.2.13_darwin_amd64.tar.gz"
      sha256 "9e4622472f052eb3041d21d85a0cb60d4ef0f8a5802e3e3175ef40be495d668f"

      def install
        bin.install "jerriedr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jkassis/jerriedr/releases/download/v0.2.13/jerriedr_0.2.13_darwin_arm64.tar.gz"
      sha256 "08d9f05f36ec0bb865ec0a706140d4e321526f29e8b71f84f26772fb45e39810"

      def install
        bin.install "jerriedr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jkassis/jerriedr/releases/download/v0.2.13/jerriedr_0.2.13_linux_arm64.tar.gz"
      sha256 "749edf387827aaac7d5688ae8aeaf32f86c8686a63b5641b4d9cc6c415ebe5fe"

      def install
        bin.install "jerriedr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jkassis/jerriedr/releases/download/v0.2.13/jerriedr_0.2.13_linux_amd64.tar.gz"
      sha256 "94ed9a48993fb9e71dd24413f734e2b5218ce3ecf7d8943c93240dd119ccd8b9"

      def install
        bin.install "jerriedr"
      end
    end
  end
end
