
# typed: false
# frozen_string_literal: true
# This file was generated by gitall.
class Gitall &lt; Formula
  desc ""
  homepage "git@github.com:jkassis/gitall.git"
  version "v0.8.10"

  on_macos do
	  
		
		

		
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
		
		

      url ".PayloadURL"
      sha256 ".PayloadSHA256"

      def install
        bin.install "gitall-darwin-10.10-amd64.tar.gz" => "gitall
      end
    end
		
		
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
		
		

		
		

      url ".PayloadURL"
      sha256 ".PayloadSHA256"

      def install
        bin.install "gitall-darwin-10.10-arm64.tar.gz" => "gitall
      end
    end
		
  end

  on_linux do
	  
		
		

		
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
		
		

      url ".PayloadURL"
      sha256 ".PayloadSHA256"

      def install
        bin.install "gitall-linux-amd64.tar.gz" => "gitall
      end
    end
		
		
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
		
		

		
		

      url ".PayloadURL"
      sha256 ".PayloadSHA256"

      def install
        bin.install "gitall-linux-arm64.tar.gz" => "gitall
      end
    end
		
  end
end
